### PR TITLE
Allow downloading pulbic dataset with Globus

### PR DESCRIPTION
**Pull request by nguyenlinhlinh**
## Description
This PR adds some small changes to Datafiles tab to allow user to download public dataset using Globus. Related PR for the backend will be available soon.
## Changes:
- This feature is enabled by giving file transfer url to variable `fileserverBaseURL` in environment.ts. For example: `fileserverBaseURL: "https://app.globus.org/file-manager?origin_id=28c034b4-1864-11e7-bb9b-22000b9a448b",`
- User navigate to Datafiles tab of the dataset he/she wants to download. Select the files and click on **Download with Globus**
- Fill in email to be contacted by SciCat once the dataset is ready to be downloaded. 
- SciCat frontend send a job request to the backend
- SciCat backend receives  the job request, creates a message and sends it to the message queue (Kafka). Our copy service copys the requested dataset to our open access endpoint in Globus.
- Once dataset is in open access endpoint SciCat sends an email to user.
- For private dataset when user click on Download with Globus the user is redirected to Globus where the files for dataset exist.
Screenshot 2022-03-11 at 10 54 04

## Tests included/Docs Updated? 
- [ ] Included for each change/fix?
- [ ] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [x] Toggle added for new features?
- [x] Requires update of catamel API?

### CODE REVIEW

**Comment by stephan271** [comment]
Just a question/thought: do we want to support download options both at the "dataset" level (as proposed here) and at the "job" level (that is what we currently do at PSI) ? Or do we want to combine the approaches under one umbrella ? For this Globus based download option: do we have a record of who downloaded what within the data catalog ?

**Comment by nguyenlinhlinh** [comment]
@stephan271 I dont know how it works for PSI under the job level but this feature creates a job request which uses the job model. Since it uses the already existed job model there will be record about who download and what files are requested. Please let me know if I havent fully understood or answered your question.

**Comment by stephan271** [comment]
AH, that is great. Yes, this answers my question.

**Review by stephan271 — APPROVED** [review]

**Review by henrikjohansson712 — CHANGES_REQUESTED** [review]
Looks good to me, you just need to add the env variable to the environment files:

```
Error: src/app/app-config.module.ts:73:38 - error TS2339: Property 'fileserverButtonLabel' does not exist on type '{ production: boolean; lbBaseURL: string; fileserverBaseURL: string; synapseBaseUrl: string; riotBaseUrl: string; jupyterHubUrl: string; externalAuthEndpoint: string; addDatasetEnabled: boolean; ... 38 more ...; retrieveDestinations: any[]; }'.

73   fileserverButtonLabel: environment.fileserverButtonLabel ?? "Download",
                                        ~~~~~~~~~~~~~~~~~~~~~
```

**Review by henrikjohansson712 — APPROVED** [review]

**Pull request merged**
