### PR TITLE
PID Search for everyone

### PR DESCRIPTION
**Pull request by TheMeinerLP**
## Description

Add for archive manager a special pid search

## Motivation

I am the son of Michael Kallmeier-Glanz he showed me the sciCat. In some points the workflow for him are non productive.
About that reason i will try to add some nice features that helps him.
## Fixes:

- None

## Changes:

- Added a PID filter for dataset view

## Tests included/Docs Updated?

- [ ] Included for each change/fix?
- [ ] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [X] Toggle added for new features?
- [ ] Requires update of SciCat backend API?

## Other 
I need littlebit help/informations how can i hide the field for non archive manager users.
And why the filter is not applying to the PID and the auto completion is empty.

### CODE REVIEW

**Comment by stephan271** [comment]
I think such a feature should be implemented for all users, not just archiveManagers.
Can you provide a screenshot /Mockup of what you plan to do and how it looks to the users ?

**Comment by TheMeinerLP** [comment]
Of course i can provide it. 
image
The code for the input is already here in the PR. But the completion and the search function of it self is not working.

**Comment by stephan271** [comment]
I think PID should not be treated as a "facet", as the other fields are, because PIDs are different for each dataset. I Think the main use case is that a user has copied a PID from somewhere and now wants to find it, so the search expression would be a simple equality check on the PID field. There is no need need to calculate any facet counts. Is this what you/Michael have in mind ?

**Comment by TheMeinerLP** [comment]
As other idea i already have to add a small icon to the pid id on general Information to copy the id more faster. But when then happend i will split into extra pr 
image

**Comment by TheMeinerLP** [comment]
> I think PID should not be treated as a "facet", as the other fields are, because PIDs are different for each dataset. I Think the main use case is that a user has copied a PID from somewhere and now wants to find it, so the search expression would be a simple equality check on the PID field. There is no need need to calculate any facet counts. Is this what you/Michael have in mind ?

Yeah thats exactly what was in my mind.

**Comment by TheMeinerLP** [comment]
How can finish implement for you. Means what needs be removed/replaced with other code?

**Comment by TheMeinerLP** [comment]
image
Final solution after some background writing with @stephan271.
Thanks for that help!

Now users can be post there PID into a field and press enter or the button inside of the text field to get direct to there dataset.

Also the system checks if the a PREFIX of Company x included. 
Mean when a use forgot like `20.500.11935/VALUE` of the selection. The tool will be added automaticlly into the request.

**Comment by nitrosx** [comment]
My apologies for jumping in last minute:
Have you considered the case where I have a partial PID? Would partial match be also useful?
We can add this as a following PR.

**Review by nitrosx — APPROVED** [review]

**Comment by TheMeinerLP** [comment]
I think thats also a good point. Can you deliver me a example i will open another PR for that 😄 
First on i will fix the github actions

**Comment by stephan271** [comment]
Just a comment to the partial PID reqiest: partial PID (substring) search will need another API endpoint using where clauses with regular expressions. However I am not sure that this is even possible on fields of type ObjectId. Also one would need to take into account that multiple datasets can be returned, therefore one would need to display the result table first before showing the dataset details.

**Comment by nitrosx** [comment]
@stephan271 : I agree with you. Partial match on id is not optimal.
When we have migrated to the BEv4.x, datasets have their id duplicated in a _pid_ field which is a simple string, so we can do it than.
I am going to approve this PR and we will open a new PR for the partial match when the time is right

**Review by nitrosx — APPROVED** [review]

**Pull request merged**
