### PR TITLE
Lazy load dataset details

### PR DESCRIPTION
**Pull request by nguyenlinhlinh**
## Description
Fetch dataset details for each tab on demand
Short description of the pull request
The dataset details are fetched all at once which make rendering of the dataset details page slow  and affect the user experience. This PR loads the data for some of the tab separately.
## Changes:
- Load and cache data of each tab on demand
- Dataset details, attachment, sample and proposal info are always fetch on init
- Data files, logbook, admin are loaded on demand
## Tests included/Docs Updated?

- [ ] Included for each change/fix?
- [ ] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [ ] Toggle added for new features?
- [x] Requires update of catamel API?

### CODE REVIEW

**Review by henrikjohansson712 — COMMENTED** [review]
Would it be possible to get this functionality without the changes to src/app/shared/sdk/services/custom/Dataset.ts? Just worried that, since it's an automatically generated file, it will be overwritten the next time we change something in the backend and regenerate the sdk.

**Comment by nguyenlinhlinh** [comment]
@henrikjohansson712 Jaha. I didn't know that. How could I get this endpoint to be generated to src/app/shared/sdk/services/custom/Dataset.ts?

**Comment by henrikjohansson712** [comment]
You would need to create the endpoint in the backend, then run the script to generate the frontend sdk, located here:  [backend/client/api/createAngularAPI.sh](https://github.com/SciCatProject/backend/blob/develop/client/api/createAngularAPI.sh).

I see that the script still says "catanie" and "catamel", so make sure to change that to "frontend" and "backend" first, and also make sure to point the output to the correct folder on your local machine.

**Comment by nguyenlinhlinh** [comment]
@henrikjohansson712 thank, I generated but then I saw that the endpoints was already generated in the old file so I reversed the changes.

**Review by henrikjohansson712 — APPROVED** [review]

**Comment by nitrosx** [comment]
@stephan271: thoughts on this PR? Can I go ahead and merge it? Thanks

**Comment by stephan271** [comment]
I like this PR, I just need to make some local tests here, which I hope I can finish today. Once this is done I let you know and you can continue to merge it.

**Review by stephan271 — APPROVED** [review]

**Comment by stephan271** [comment]
LGTM, please go ahead with merging.

**Pull request merged**
