### PR TITLE
Chore/proposals view model selectors

### PR DESCRIPTION
**Pull request by henrikjohansson712**
## Description

Replaces individual selectors in the proposals module with view model selectors. Plan is to do this for every component in the app.

## Motivation

Each view will now just make a single call to the store to get data. Easier to work with and easier to test as there will only be one async variable in each view.

## Changes:

* Create selectViewProposalPageViewModel selector
* Replace individual selectors in view proposal page component with selectViewProposalPageViewModel selector
* Remove old proposal dashboard component
* Rename proposal dashboard new component to proposal dashboard component

## Tests included/Docs Updated?

- [x] Included for each change/fix?
- [x] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [ ] Toggle added for new features?
- [ ] Requires update of catamel API?

### CODE REVIEW

**Comment by nguyenlinhlinh** [comment]
Hi @henrikjohansson712, I think you makes the changes in the old proposal-dashboard component. The new one is proposal-dashboard-new. Should we decide to use one of them and remove the other? (Question for both @henrikjohansson712 & @minottic)

**Comment by henrikjohansson712** [comment]
Yes, I made the changes there as that component is still in there. The new component doesn't use selectors. I'm all for removing the old one.

**Comment by nguyenlinhlinh** [comment]
I guess we can then remove the component since it was Stephan who asked to change the table view in it.

**Comment by stephan271** [comment]
Fine for me to delete the old one

**Comment by henrikjohansson712** [comment]
Done!

**Review by nguyenlinhlinh — APPROVED** [review]

**Review by nitrosx — APPROVED** [review]

**Pull request merged**
