### PR TITLE
Hotfix/token prefix config

### PR DESCRIPTION
**Pull request by henrikjohansson712**
## Description

New backend uses Bearer tokens. This PR adds an `accessTokenPrefix` config property that should be set to "Bearer " when using the new backend and just an empty string when using the old backend.

## Motivation

Make Frontend compatible with both backends.

## Changes:

* Add `accessTokenPrefix` config prop to app config service
* Implement logic to set prefix in user effects

## Tests included/Docs Updated?

- [ ] Included for each change/fix?
- [x] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [ ] Toggle added for new features?
- [ ] Requires update of catamel API?

### CODE REVIEW

**Comment by nitrosx** [comment]
@nguyenlinhlinh , @dylanmcreynolds and @minottic: could you please review this PR and approve it if it is ready?

**Review by nguyenlinhlinh — APPROVED** [review]

**Review by minottic — APPROVED** [review]
LGTM. Only comment: is there a reason why whenever there is a new config option we make it mandatory to specify it? Couldn't we fallback to "" if not specified? I think that makes it easier to upgrade to newer versions without needing to change the config file (or needing to know all the config file+ effects changes)

**Comment by nitrosx** [comment]
@henrikjohansson712 Could you please address the question from @minottic ?
@dylanmcreynolds Could you please review and approve this PR?

**Comment by henrikjohansson712** [comment]
@minottic Because we're using Typescript. If we don't specify the variable, then it becomes pretty much impossible to access, which is annoying.

**Comment by minottic** [comment]
ah ok, thanks. But I am pretty sure I've done that in here: #887 , maybe then it's not the best way?

**Pull request merged**
