### PR TITLE
Child routes

### PR DESCRIPTION
**Pull request by nguyenlinhlinh**
## Description
Add child routes for tabs in `dataset-details-dashboard.component.ts`.
See #848 for more information
## Motivation
See #848 
## Fixes:
- Add child routes
- Refactor the code in `dataset-details-dashboard.component.ts`. Delegate the logic parts to sub components in each tab
## For reviewers
- I want to disable the routes if  the value for a give feature is disabled in `environment.ts` for example route `.../logbook` should not exists if `logbookEnabled = false`. However I can't find out how to import the appConfig to `src/app/app-routing/lazy/dataset-details-dashboard-routing/dataset-details-dashboard.routing.module.ts`. Please let me know if you know how to do that.
- Please check that the functions supported on each tab works properly. We don't have all the supported features so I am unable to test all tabs
- Check that tabs for unused features don't show up and tabs for public dataset and private dataset are showed up or hided correctly. 
## Tests included/Docs Updated?

- [x] Included for each change/fix?
- [x] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [ ] Toggle added for new features?
- [ ] Requires update of catamel API?

### CODE REVIEW

**Comment by stephan271** [comment]
Hi Linh, checked the tabs and all looks nice here, thanks. Concerning your environment question: I am not sure if I understand the question correctly, but maybe this link helps ? https://stackoverflow.com/questions/51056704/configure-angular-routes-in-environment

**Comment by nguyenlinhlinh** [comment]
@stephan271 Thank for the link. The link is what I am searching for even though my initial idea was not the same. Because I didn't know what to search for in Angular so I though I could somehow filter the list of routes using appConfig. The Stackoverflow solution looks better.

**Comment by stephan271** [comment]
Glad I could help :-)

**Comment by stephan271** [comment]
The findOne call on the dataset still fetches the full information ({"where":{"pid":"20.500.11935/3ab12715-2ae5-4a8e-9c38-c1d2375bd528"},"include":[{"relation":"origdatablocks"},{"relation":"datablocks"},{"relation":"attachments"}]} already when entering the dataset details overview. Could one also load the data lazily, i.e. add the {"relation":"origdatablocks"} etc only when the corresponding tab is selected ?

**Comment by nguyenlinhlinh** [comment]
@stephan271 It is possible to load the data on demand. Since the task is about child routes I just make changes to be able to create child routes and preserve the logic for handling data untouched. But I can make changes so that the data is loaded lazily.

**Comment by stephan271** [comment]
For us being able to load the data lazily is quite critical, because otherwise the browser starts to become unresponsive for datasets with many files. But doing this in a second PR would of course also be good, in fact I would recommend doing it in 2 steps, i.e. in a 2nd PR.

**Comment by nguyenlinhlinh** [comment]
Ok, I will work on the second PR.

**Review by stephan271 — APPROVED** [review]

**Review by henrikjohansson712 — APPROVED** [review]

**Pull request merged**
