### PR TITLE
Fix proposal for #1135

### PR DESCRIPTION
**Pull request by fpotier**
See #1135

### CODE REVIEW

**Comment by fpotier** [comment]
Note that this patch requires to update the deployment's config

**Comment by nitrosx** [comment]
@fpotier would you be able to expand the functionality in the following way:

- If no configuration value is provided under the key "logo-icon", you use the assets/images/site-logo.png, otherwise you inject the value provide in configuration
- Update/Create documentation so we explain the configuration variable and value, and also we provide example on how to mount the logo image into the docker container.

Please let me know if it makes sense, or I should elaborate on it.

**Comment by fpotier** [comment]
@nitrosx Should this new configuration key `logo-icon` contain the absolute path of the asset or we just assume it's a file in `assets/images`?

Where should I write the associated documentation?

**Comment by nitrosx** [comment]
@fpotier let's assume that it leaves in `assets/images`.

You can find the documentation in repo https://github.com/SciCatProject/documentation.
Most likely goes under the Operator section.

**Comment by nitrosx** [comment]
@fpotier please let me know if my comment makes sense

**Comment by fpotier** [comment]
@nitrosx Yes it does, now it should work as you asked

**Review by nitrosx — APPROVED** [review]

**Pull request merged**
