### PR TITLE
fix: changed env var naming for create sample button from edit to add

### PR DESCRIPTION
**Pull request by Junjiequan**
## Description

Depends on https://github.com/SciCatProject/scicat-backend-next/pull/1103

## Motivation

Background on use case, changes needed

## Fixes:

* Items added

## Changes:

* changes made

## Tests included/Docs Updated?

- [ ] Included for each change/fix?
- [ ] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [ ] Toggle added for new features?
- [ ] Requires update of SciCat backend API?

### CODE REVIEW

**Comment by bpedersen2** [comment]
cypress tests need adoption to changed element name, otherwise looks fine

```
 1) Datasets general
       Create dataset
         should be able to create dataset in the UI:
     AssertionError: Timed out retrying after 10000ms: Expected to find element: `mat-card.add-card`, but never found it.
      at Context.eval (webpack:///../../../cypress/e2e/datasets/datasets-general.cy.js:24:9)
```

**Comment by Junjiequan** [comment]
I will remove Create Dataset and Create sample from the E2E test, because creating dataset and sample form on the UI is incomplete and only supports limited fields. After we improved the form we can then put the test back again.

**Comment by Junjiequan** [comment]
I will remove Create Dataset and Create sample from the E2E test, because creating dataset and sample form on the UI is incomplete and only supports limited fields. After we improved the form we can then put the test back again.

**Comment by bpedersen2** [comment]
> I will remove Create Dataset and Create sample from the E2E test, because creating dataset and sample form on the UI is incomplete and only supports limited fields. After we improved the form we can then put the test back again.

Thats OK

**Pull request merged**
